### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by richjdsmith** [felixholzmeister/bret#3]
Hey Felix, 

Any chance you could add the parent settings.py file for oTree?

**Comment by felixholzmeister** [comment]
Hi,

actually, you only need to add the session configuration to settings.py, just as for any other app you run in oTree. (See the [documentation](http://www.holzmeister.biz/downloads/bret/Documentation.pdf) for an example how to specify the session config.)

If you face any problems, please get in touch via e-mail (felix.holzmeister@uibk.ac.at) and I'll forward you the settings.py file directly.

**Comment by richjdsmith** [comment]
Thank you!
